#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 timbergeron
"""Stage the HUD font, or rebuild the bundled DejaVu Sans atlas.

Normal builds need only Python's standard library. To regenerate the font:
python3 hud_assets.py --font
This optional operation requires libcairo and DejaVu Sans (Debian packages
libcairo2 and fonts-dejavu-core). Font licensing is in resources/ui/LICENSE.txt.
"""

import argparse
import ctypes as ct
import ctypes.util
from pathlib import Path
import shutil
import struct


HERE = Path(__file__).resolve().parent


def write_tga(path, width, height, pixels):
    header = bytearray(18)
    header[2] = 2
    struct.pack_into("<HH", header, 12, width, height)
    header[16:18] = bytes((32, 0x28))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(header + bytes(channel for pixel in pixels
                                   for channel in (pixel[2], pixel[1], pixel[0], pixel[3])))


def generate(destination):
    destination.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(HERE / "resources/ui/bv_ui.tga", destination / "bv_ui.tga")


def generate_font():
    """Bake 32 px glyph cells and matching advances; never needed at runtime."""
    cairo = ct.CDLL(ctypes.util.find_library("cairo"))

    def bind(name, restype, *argtypes):
        fn = getattr(cairo, "cairo_" + name)
        fn.restype, fn.argtypes = restype, argtypes
        return fn

    class Extents(ct.Structure):
        _fields_ = [(name, ct.c_double) for name in
                    ("x_bearing", "y_bearing", "width", "height", "x_advance", "y_advance")]

    pointer, number = ct.c_void_p, ct.c_double
    surface = bind("image_surface_create", pointer, ct.c_int, ct.c_int, ct.c_int)(2, 512, 512)
    context = bind("create", pointer, pointer)(surface)
    bind("select_font_face", None, pointer, ct.c_char_p, ct.c_int, ct.c_int)(
        context, b"DejaVu Sans", 0, 0)
    bind("set_font_size", None, pointer, number)(context, 28)
    bind("set_source_rgba", None, pointer, number, number, number, number)(context, 1, 1, 1, 1)
    move = bind("move_to", None, pointer, number, number)
    show = bind("show_text", None, pointer, ct.c_char_p)
    save = bind("save", None, pointer)
    restore = bind("restore", None, pointer)
    rectangle = bind("rectangle", None, pointer, number, number, number, number)
    clip = bind("clip", None, pointer)
    measure = bind("text_extents", None, pointer, ct.c_char_p, ct.POINTER(Extents))
    advances = []
    for code in range(32, 127):
        character = chr(code).encode("ascii")
        extent = Extents()
        measure(context, character, ct.byref(extent))
        advances.append(round(extent.x_advance))
        ox, oy = (code % 16) * 32, (code // 16) * 32
        # A transparent texel gutter prevents adjacent glyphs bleeding when
        # the engine linearly filters a scaled subsection of the atlas.
        save(context)
        rectangle(context, ox + 1, oy + 1, 30, 30)
        clip(context)
        move(context, ox + 1, oy + 24)
        show(context, character)
        restore(context)
    bind("surface_flush", None, pointer)(surface)
    data = bind("image_surface_get_data", ct.POINTER(ct.c_ubyte), pointer)(surface)
    stride = bind("image_surface_get_stride", ct.c_int, pointer)(surface)
    write_tga(HERE / "resources/ui/bv_ui.tga", 512, 512,
              [(255, 255, 255, data[y * stride + x]) for y in range(512) for x in range(512)])
    bind("destroy", None, pointer)(context)
    bind("surface_destroy", None, pointer)(surface)
    # Printable ASCII encodes each advance plus 33. Escape QC string syntax.
    widths = "".join(chr(value + 33) for value in advances).replace("\\", "\\\\").replace('"', '\\"')
    (HERE / "src/hud_metrics.qc").write_text(
        "// Generated by hud_assets.py --font; DejaVu Sans, see resources/ui/LICENSE.txt.\n"
        "float(float character) BV_GlyphAdvance =\n{\n"
        "    if (character < 32 || character > 126) character = 63;\n"
        f'    return (str2chr("{widths}", character - 32) - 33) / 32;\n'
        "};\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", action="store_true")
    args = parser.parse_args()
    if args.font:
        generate_font()
    else:
        generate(HERE / "dist/beachvolley/gfx")
